.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH mode 1  "mode " 
.SH NAME
mode \- Show regin\*(Aqs effective operating mode: org (supervisor) vs standalone (FEAT\-041)
.SH SYNOPSIS
\fBmode\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show regin\*(Aqs effective operating mode: org (supervisor) vs standalone (FEAT\-041)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
