.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH checks 1  "checks " 
.SH NAME
checks \- List active derived (promoted) deterministic checks (FEAT\-051)
.SH SYNOPSIS
\fBchecks\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List active derived (promoted) deterministic checks (FEAT\-051)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
