#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    # Remove state and config
    rm -rf /var/lib/regin
    rm -rf /etc/regin
    # Remove system user
    deluser --quiet regin 2>/dev/null || true
fi

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload
fi

#DEBHELPER#
exit 0
